import "./globals.css";

import { Inter } from "next/font/google";
import { ReduxProvider } from "@/components/ReduxProvider";
import RootLayout from "@/components/layouts/root/Root.layout";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Demo App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function Root({ children }: { children: ReactNode }) {
  return (
    <html suppressHydrationWarning lang="en" className="bg-zinc-900 !text-white">
      <body className={`${inter.className} min-h-screen`}>
        <ReduxProvider>
          <RootLayout>{children}</RootLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
